#!/usr/bin/env python3
"""Silence the 8,000 "Character flag 'item_gen_*' is set but is never used"
lint warnings that appeared after the slot-based shop refactor.

Nothing reads flag:item_gen_* literals anymore (reads go through variables and
saved scopes), so the usage analyzer flags every generated item. This script
emits a scripted trigger that references each flag once, and wires it into
omni_assign_generated_items_rarities behind `always = no`, so it is compiled
(registering the flags as used) but never evaluated at runtime.

Run from the mod root after regenerate_generated_items.py:
  python3 Scripts/generate_item_flag_registry.py
"""
import re, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RAND = os.path.join(ROOT, 'common', 'scripted_effects', 'omniluxia_random_items_effects.txt')
REG = os.path.join(ROOT, 'common', 'scripted_triggers', 'omni_gen_items_flag_registry.txt')

GUARD = '\tif = { limit = { always = no omni_gen_items_flag_use_registry = yes } }'

src = open(RAND, encoding='utf-8-sig').read()
pairs = re.findall(r'add_to_global_variable_list = \{ name = (item_\w+_rarity) target = flag:(item_gen_\w+) \}', src)
assert len(pairs) == 8000, len(pairs)

out = ['# Auto-generated by Scripts/generate_item_flag_registry.py — do not hand edit.',
       '# Never evaluated at runtime: referenced only behind `always = no` in',
       '# omni_assign_generated_items_rarities so each generated item flag counts',
       "# as 'used' and the loader stops logging 8,000 lint warnings.",
       '',
       'omni_gen_items_flag_use_registry = {',
       '\tOR = {']
for rar, item in pairs:
    out.append(f'\t\tis_target_in_global_variable_list = {{ name = {rar} target = flag:{item} }}')
out += ['\t}', '}', '']
open(REG, 'w', encoding='utf-8-sig', newline='\n').write('\n'.join(out))

if 'omni_gen_items_flag_use_registry' not in src:
    anchor = 'omni_assign_generated_items_rarities = {'
    if anchor not in src:
        sys.exit('rarities effect not found')
    src = src.replace(anchor, anchor + '\n' + GUARD, 1)
    open(RAND, 'w', encoding='utf-8-sig', newline='\n').write(src)
    print('guard inserted')
print(f'registry written with {len(pairs)} flags')
