#!/usr/bin/env python3
"""Regenerate the generated-item script files in a load-time-friendly form.

The old form enumerated all 8,000 item_gen_* items as:
  - 8,000 single-line options in event omni_items.6 (the shop menu)
  - giant per-culture-group random_lists in the shop roll effects
  - giant per-culture-group random_lists in the adventure loot effects
  - 16,000 parameterized wrapper calls for category/rarity assignment

That made the event database take ~70s to build (and rebuild on every hot
reload). The new form keeps identical item pools, weights, prices and
distributions, but:
  - assignment effects add items to per-culture-group global "pool" lists
    (omni_gen_pool_<group>_<rarity>) alongside the existing item_<rarity> and
    item_<category> lists
  - roll effects pick uniformly from those pools via random_in_global_list
  - the shop menu shows generated items through 10 dynamic slot options
    (omni_shop_slot_1..10 character variables) instead of 8,000 static options

Run from the mod root:  python3 Scripts/regenerate_generated_items.py
"""
import re, sys, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EFF = os.path.join(ROOT, 'common', 'scripted_effects')
RAND = os.path.join(EFF, 'omniluxia_random_items_effects.txt')
ADV = os.path.join(EFF, 'OMNI_adventure_generated_items_effects.txt')
HELPERS = os.path.join(EFF, 'omni_gen_slot_helpers.txt')
MENU = os.path.join(ROOT, 'events', 'omni_item_menu.txt')
LOC = os.path.join(ROOT, 'localization', 'english', 'Omniluxia', 'omni_gen_slots_l_english.yml')

RARITIES = ['common_rarity', 'uncommon_rarity', 'rare_rarity']
PRICES = {'common_rarity': 60, 'uncommon_rarity': 120, 'rare_rarity': 200}
N_SLOTS = 10

def read(p):
    with open(p, encoding='utf-8-sig') as f:
        return f.read()

def write(p, s):
    with open(p, 'w', encoding='utf-8-sig', newline='\n') as f:
        f.write(s)

def extract_effect(src, name):
    m = re.search(r'^' + re.escape(name) + r'\s*=\s*\{', src, re.M)
    if not m:
        sys.exit(f'effect {name} not found')
    depth, i = 0, m.start()
    body = src[m.start():]
    for j, ch in enumerate(body):
        if ch == '{': depth += 1
        elif ch == '}':
            depth -= 1
            if depth == 0:
                return body[:j+1]
    sys.exit(f'unbalanced effect {name}')

# ---------------------------------------------------------------- parse
rand_src = read(RAND)
adv_src = read(ADV)

categories = re.findall(r'assing_item_to_category = \{ item_category = (\w+) item_ID = (\w+) \}', rand_src)
rarities = re.findall(r'assing_item_to_rarity = \{ item_rarity = (\w+) item_ID = (\w+) \}', rand_src)
item_rarity = {i: r for r, i in rarities}
item_cat = {i: c for c, i in categories}
assert len(item_rarity) == 8000, len(item_rarity)
assert len(item_cat) == 8000, len(item_cat)

# per-rarity, ordered group -> items, from the roll effects
pools = {}   # (group, rarity) -> [items]
group_order = []
for rar, eff in [('common_rarity', 'omni_roll_generated_common_shop_item'),
                 ('uncommon_rarity', 'omni_roll_generated_uncommon_shop_item'),
                 ('rare_rarity', 'omni_roll_generated_rare_shop_item')]:
    body = extract_effect(rand_src, eff)
    chunks = re.split(r'country_culture_group = (\w+)', body)
    for g, chunk in zip(chunks[1::2], chunks[2::2]):
        items = re.findall(r'item_ID = (item_gen_\w+)', chunk)
        assert items, (eff, g)
        pools[(g, rar)] = items
        if g not in group_order:
            group_order.append(g)
        for it in items:
            assert item_rarity[it] == rar, (it, rar, item_rarity[it])
assert len(group_order) == 80, len(group_order)
assert sum(len(v) for v in pools.values()) == 8000

# curated (non-generated) fallback branches in the adventure effects
adv_curated = {}
for rar, eff in [('common_rarity', 'omni_adventure_roll_generated_common_item_effect'),
                 ('uncommon_rarity', 'omni_adventure_roll_generated_uncommon_item_effect'),
                 ('rare_rarity', 'omni_adventure_roll_generated_rare_item_effect')]:
    body = extract_effect(adv_src, eff)
    curated = [i for i in re.findall(r'give_character_an_item = \{ item_ID = (\w+) \}', body)
               if not i.startswith('item_gen_')]
    assert curated, eff
    adv_curated[rar] = curated

# ------------------------------------------- 1. assignment + roll effects
out = ['# Auto-generated by Scripts/regenerate_generated_items.py — do not hand edit.',
       '# Adds every generated item to its category/rarity lists and to a per-',
       '# culture-group pool list used by the compact roll effects below.', '']
out.append('omni_assign_generated_items_categories = {')
for g in group_order:
    for rar in RARITIES:
        for it in pools[(g, rar)]:
            out.append(f'\tadd_to_global_variable_list = {{ name = item_{item_cat[it]} target = flag:{it} }}')
out.append('}')
out.append('')
out.append('omni_assign_generated_items_rarities = {')
for g in group_order:
    for rar in RARITIES:
        for it in pools[(g, rar)]:
            out.append(f'\tadd_to_global_variable_list = {{ name = item_{rar} target = flag:{it} }}')
            out.append(f'\tadd_to_global_variable_list = {{ name = omni_gen_pool_{g}_{rar} target = flag:{it} }}')
out.append('}')
for rar, eff in [('common_rarity', 'omni_roll_generated_common_shop_item'),
                 ('uncommon_rarity', 'omni_roll_generated_uncommon_shop_item'),
                 ('rare_rarity', 'omni_roll_generated_rare_shop_item')]:
    out.append('')
    out.append(f'{eff} = {{')
    for g in group_order:
        out.append(f'\tif = {{ limit = {{ country_culture_group = {g} }} omni_pick_gen_stock_item = {{ POOL = omni_gen_pool_{g}_{rar} }} }}')
    out.append('}')
write(RAND, '\n'.join(out) + '\n')

# ------------------------------------------------- 2. adventure effects
out = ['# Auto-generated by Scripts/regenerate_generated_items.py — do not hand edit.',
       '# Adventure loot: picks one of the 80 culture groups (plus a curated',
       '# fallback pool weighted like one group) uniformly, then a uniform item',
       '# of the requested rarity from that pool. Identical distribution to the',
       '# old enumerated random_lists.', '']
for rar, eff in [('common_rarity', 'omni_adventure_roll_generated_common_item_effect'),
                 ('uncommon_rarity', 'omni_adventure_roll_generated_uncommon_item_effect'),
                 ('rare_rarity', 'omni_adventure_roll_generated_rare_item_effect')]:
    out.append(f'{eff} = {{')
    out.append('\trandom_list = {')
    for g in group_order:
        out.append(f'\t\t1 = {{ omni_adventure_pick_gen_item = {{ POOL = omni_gen_pool_{g}_{rar} }} }}')
    out.append('\t\t1 = {')
    out.append('\t\t\trandom_list = {')
    for it in adv_curated[rar]:
        out.append(f'\t\t\t\t1 = {{ ROOT = {{ give_character_an_item = {{ item_ID = {it} }} }} }}')
    out.append('\t\t\t}')
    out.append('\t\t}')
    out.append('\t}')
    out.append('}')
    out.append('')
write(ADV, '\n'.join(out) + '\n')

# ------------------------------------------------------- 3. helper effects
slot_buy_rar = (
    f'\tif = {{ limit = {{ is_target_in_global_variable_list = {{ name = item_common_rarity target = var:omni_shop_slot_$SLOT$ }} }} add_gold = -{PRICES["common_rarity"]} }}\n'
    f'\telse_if = {{ limit = {{ is_target_in_global_variable_list = {{ name = item_uncommon_rarity target = var:omni_shop_slot_$SLOT$ }} }} add_gold = -{PRICES["uncommon_rarity"]} }}\n'
    f'\telse = {{ add_gold = -{PRICES["rare_rarity"]} }}')
helpers = f'''# Auto-generated by Scripts/regenerate_generated_items.py — do not hand edit.
# Scope-target helpers for the generated-item shop slots and adventure loot.

# Picks a uniform random item from a generated-item pool and tries to stock it.
# Mirrors omni_add_item_to_shop_stock, but takes the item as a saved scope so a
# single effect serves all 8,000 items.
omni_pick_gen_stock_item = {{
\trandom_in_global_list = {{
\t\tvariable = $POOL$
\t\tsave_scope_as = omni_gen_item_pick
\t}}
\tif = {{
\t\tlimit = {{ exists = scope:omni_gen_item_pick }}
\t\tomni_add_scoped_item_to_shop_stock = yes
\t}}
}}

omni_add_scoped_item_to_shop_stock = {{
\tscope:omni_shop_owner = {{
\t\tif = {{
\t\t\tlimit = {{
\t\t\t\tNOT = {{ is_target_in_variable_list = {{ name = omni_item_shop_stock target = scope:omni_gen_item_pick }} }}
\t\t\t\tOR = {{
\t\t\t\t\tAND = {{ var:omni_shop_max_items = 4 var:omni_shop_item_count < 4 }}
\t\t\t\t\tAND = {{ var:omni_shop_max_items = 6 var:omni_shop_item_count < 6 }}
\t\t\t\t\tAND = {{ var:omni_shop_max_items = 8 var:omni_shop_item_count < 8 }}
\t\t\t\t\tAND = {{ var:omni_shop_max_items = 10 var:omni_shop_item_count < 10 }}
\t\t\t\t}}
\t\t\t}}
\t\t\tadd_to_variable_list = {{ name = omni_item_shop_stock target = scope:omni_gen_item_pick }}
\t\t\tadd_to_variable_list = {{ name = omni_item_shop_stock_gen target = scope:omni_gen_item_pick }}
\t\t\tchange_variable = {{ name = omni_shop_item_count add = 1 }}
\t\t}}
\t}}
}}

# Buys the generated item held in character variable omni_shop_slot_$SLOT$.
# Price by rarity matches the old per-item options (60/120/200).
omni_buy_generated_slot_item = {{
{slot_buy_rar}
\tif = {{
\t\tlimit = {{ NOT = {{ is_target_in_variable_list = {{ name = item_list target = var:omni_shop_slot_$SLOT$ }} }} }}
\t\tadd_to_variable_list = {{ name = item_list target = var:omni_shop_slot_$SLOT$ }}
\t}}
\tremove_list_variable = {{ name = omni_item_shop_stock target = var:omni_shop_slot_$SLOT$ }}
\tremove_list_variable = {{ name = omni_item_shop_stock_gen target = var:omni_shop_slot_$SLOT$ }}
\tremove_variable = omni_shop_slot_$SLOT$
}}

# Adventure loot: pick from a pool and hand straight to ROOT (the adventurer).
omni_adventure_pick_gen_item = {{
\trandom_in_global_list = {{
\t\tvariable = $POOL$
\t\tsave_scope_as = omni_gen_item_pick
\t}}
\tif = {{
\t\tlimit = {{ exists = scope:omni_gen_item_pick }}
\t\tROOT = {{ omni_give_scoped_gen_item = yes }}
\t}}
}}

omni_give_scoped_gen_item = {{
\tif = {{
\t\tlimit = {{ NOT = {{ is_target_in_variable_list = {{ name = item_list target = scope:omni_gen_item_pick }} }} }}
\t\tadd_to_variable_list = {{ name = item_list target = scope:omni_gen_item_pick }}
\t}}
}}
'''
write(HELPERS, helpers)

# ------------------------------------------------------------- 4. menu event
menu = read(MENU).split('\n')

start = next(i for i, l in enumerate(menu) if l.startswith('omni_items.6 = {'))
end = next(i for i, l in enumerate(menu[start+1:], start+1) if re.match(r'omni_items\.\d+ = \{', l))

# 4a. drop the 8,000 single-line generated options
gen_opt = re.compile(r'^\s*option = \{.*item_gen_.*\}\s*$')
region = menu[start:end]
kept, first_gen, removed = [], None, 0
for l in region:
    if gen_opt.match(l):
        if first_gen is None:
            first_gen = len(kept)
        removed += 1
    else:
        kept.append(l)
assert removed == 8000, removed

# 4b. slot options where the generated options used to sit
slot_opts = []
for n in range(1, N_SLOTS + 1):
    slot_opts.append(
        f'\toption = {{ name = omni_items.6.gslot{n} trigger = {{ has_variable = omni_shop_slot_{n} '
        f'NOT = {{ is_target_in_variable_list = {{ name = item_list target = var:omni_shop_slot_{n} }} }} '
        f'OR = {{ '
        f'AND = {{ is_target_in_global_variable_list = {{ name = item_common_rarity target = var:omni_shop_slot_{n} }} wealth >= {PRICES["common_rarity"]} }} '
        f'AND = {{ is_target_in_global_variable_list = {{ name = item_uncommon_rarity target = var:omni_shop_slot_{n} }} wealth >= {PRICES["uncommon_rarity"]} }} '
        f'AND = {{ is_target_in_global_variable_list = {{ name = item_rare_rarity target = var:omni_shop_slot_{n} }} wealth >= {PRICES["rare_rarity"]} }} '
        f'}} }} '
        f'custom_tooltip = omni_items_gslot{n}_desc '
        f'omni_buy_generated_slot_item = {{ SLOT = {n} }} '
        f'trigger_event = {{ id = omni_items.6 }} }}')
kept[first_gen:first_gen] = slot_opts

# 4c. rebuild slot variables every time the event fires
build_line = next(i for i, l in enumerate(kept) if 'omni_build_item_shop_stock = yes' in l)
if_line = next(i for i in range(build_line, -1, -1) if kept[i].strip() == 'if = {')
depth = 0
for i in range(if_line, len(kept)):
    depth += kept[i].count('{') - kept[i].count('}')
    if depth == 0:
        insert_at = i + 1
        break
deriv = ['\t\t\t# Rebuild generated-item slot variables from the persisted stock list']
deriv += [f'\t\t\tremove_variable = omni_shop_slot_{n}' for n in range(1, N_SLOTS + 1)]
deriv.append('\t\t\tset_variable = { name = omni_slot_cursor value = 0 }')
deriv.append('\t\t\tevery_in_list = {')
deriv.append('\t\t\t\tvariable = omni_item_shop_stock_gen')
deriv.append('\t\t\t\troot = {')
deriv.append('\t\t\t\t\tchange_variable = { name = omni_slot_cursor add = 1 }')
for n in range(1, N_SLOTS + 1):
    kw = 'if' if n == 1 else 'else_if'
    deriv.append(f'\t\t\t\t\t{kw} = {{ limit = {{ var:omni_slot_cursor = {n} }} set_variable = {{ name = omni_shop_slot_{n} value = prev }} }}')
deriv.append('\t\t\t\t}')
deriv.append('\t\t\t}')
deriv.append('\t\t\tremove_variable = omni_slot_cursor')
kept[insert_at:insert_at] = deriv

menu[start:end] = kept
write(MENU, '\n'.join(menu))

# ------------------------------------------------------------------ 5. loc
loc = ['﻿l_english:']
loc.append(' omni_items_gslot_missing:0 "a mysterious ware"')
for n in range(1, N_SLOTS + 1):
    loc.append(f' omni_items.6.gslot{n}:0 "[SelectLocalization(\'(bool)yes\',ROOT.GetCharacter.MakeScope.Var(\'omni_shop_slot_{n}\').GetFlagName,\'omni_items_gslot_missing\')]"')
for n in range(1, N_SLOTS + 1):
    loc.append(f' omni_items_gslot{n}_desc:0 "[SelectLocalization(\'(bool)yes\',Concatenate(ROOT.GetCharacter.MakeScope.Var(\'omni_shop_slot_{n}\').GetFlagName,\'_desc\'),\'omni_items_gslot_missing\')]"')
with open(LOC, 'w', encoding='utf-8', newline='\n') as f:
    f.write('\n'.join(loc) + '\n')

print(f'groups: {len(group_order)}, items: {len(item_rarity)}, removed options: {removed}')
for rar in RARITIES:
    print(rar, sum(len(pools[(g, rar)]) for g in group_order), 'curated', len(adv_curated[rar]))
print('done')
